server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8081}
          predicates:
            - Path=/api/auth/**

        - id: presenca-service
          uri: ${PRESENCA_SERVICE_URL:http://presenca-service:8082}
          predicates:
            - Path=/api/v1/**

        - id: register-adm-service
          uri: ${REGISTER_ADM_SERVICE_URL:http://register-adm-service:8084}
          predicates:
            - Path=/admin/**,/alunos/**,/motoristas/**,/veiculos/**,/eleicao/**

        - id: relatorio-service
          uri: ${RELATORIO_SERVICE_URL:http://relatorio-service:8083}
          predicates:
            - Path=/api/relatorios/**,/api/sync/**,/api/metricas/**,/api/indicadores/**

jwt:
  secret: ${JWT_SECRET}
